### ISSUE TITLE
clipboardy error

### ISSUE THREAD

**Issue by ryw** [ameerthehacker/kubelive#3]
Ran `npm install -g kubelive`

Then `kubelive` gives me error:

```
/Users/ry/.nvm/versions/node/v8.0.0/lib/node_modules/kubelive/node_modules/clipboardy/lib/macos.js:5
	...process.env,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ry/.nvm/versions/node/v8.0.0/lib/node_modules/kubelive/node_modules/clipboardy/index.js:4:15)
```

**Comment by ameerthehacker** [comment]
@ryw what is your node version

**Comment by ryw** [comment]
wow v8.0.0 - new computer, maybe i need to upgrade :)

**Comment by ameerthehacker** [comment]
@ryw yes please try upgrading and let me know

**Comment by ryw** [comment]
upgraded to v10.16.3, works
