### ISSUE TITLE
ENOENT: no such file or directory on macOS

### ISSUE THREAD

**Issue by Dentrax** [ameerthehacker/kubelive#35]
**Describe the bug**
Does not work because of `yoga-layout-prebuilt`, i think. Fresh installed `npm`.

**To Reproduce**

1. `npm install -g kubelive`
2. `kubelive get pods`
3. See error:

```bash
/usr/local/lib/node_modules/kubelive/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at KubeConfig.loadFromFile (/usr/local/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config.js:69:32)
    at KubeConfig.loadFromDefault (/usr/local/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config.js:202:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/kubelive/src/kube/api.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}
```

**Expected behavior**
Should work?

**Screenshots**
<img width="1573" alt="Screen Shot 2020-07-14 at 09 37 18" src="https://user-images.githubusercontent.com/16493751/87392680-9e12b500-c5b5-11ea-928b-806b27c6f2da.png">

*npm --version:* `6.14.6`

**Comment by ameerthehacker** [comment]
@Dentrax what node version, are you using? and is your kubeconfig in the right place?

**Comment by Dentrax** [comment]
Yes, in the right place.

*node --version:* `v14.5.0`
*echo $KUBECONFIG:*: `:/Users/furkan/.kube/config`

**Comment by ameerthehacker** [comment]
@Dentrax can you try with node v10

**Comment by Dentrax** [comment]
Honestly, i don't like JS things like npm and node etc. But I think, I shouldn't downgrade the version, instead, it should support latest version of node, as you said in readme: `node v10 or higher`.

**Comment by ameerthehacker** [comment]
@Dentrax sorry for your inconvenience but it is impossible to test in all node version above v10 and to know whether it is a version problem for sure you need to help me by trying it on node 10 but if it is up to you to do so.

thanks
