### ISSUE TITLE
Unable to run on Cygwin

### ISSUE THREAD

**Issue by kk2526** [ameerthehacker/kubelive#42]
**Describe the bug**
Unable to run on Cygwin

**To Reproduce**
Able to run help/version commands but unable to run rest of them.

```
$ kubelive -v
1.5.0
```

**Screenshots**
```
$ kubelive get pod
Warning: Failed prop type: The prop `isRawModeSupported` is marked as required in `TabsWithStdin`, but its value is `undefined`.
    in TabsWithStdin (created by Context.Consumer)
    in Tabs (created by NamespacesComponent)
    in NamespacesComponent (created by Namespaces)
    in Namespaces (created by App)
    in App
    in App
The above error occurred in the <TableComponent> component:
    in TableComponent (created by PodsComponent)
    in PodsComponent (created by BaseContainer)
    in BaseContainer (created by Pods)
    in Pods (created by Context.Consumer)
    in App
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
(node:27136) UnhandledPromiseRejectionWarning: Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
    at Object.setRawMode (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\ink\build\components\App.js:48:17)
    at TableComponent.componentDidMount (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\src\components\table.js:54:16)
    at commitLifeCycles (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:12096:22)
    at commitLayoutEffects (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:15342:7)
    at Object.invokeGuardedCallbackImpl (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:11563:10)
    at invokeGuardedCallback (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:11740:31)
    at commitRootImpl (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:15080:9)
    at unstable_runWithPriority (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\scheduler\cjs\scheduler.development.js:697:12)
    at runWithPriority (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:1881:10)
    at commitRoot (C:\Users\kkhanna\AppData\Roaming\npm\node_modules\kubelive\node_modules\react-reconciler\cjs\react-reconciler.development.js:14920:3)
(node:27136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Namespaces (created by App)
    in App
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in App

```

**Desktop (please complete the following information):**

- OS: Windows 10
- Version [e.g. 22] 1.5.0
```
$ node -v
v12.18.2
```
```
$ npm -v
6.14.5
```

**Additional context**

**Comment by ameerthehacker** [comment]
Thanks for reporting this @kk2526, I think I know where the bug is, will keep you updated
